### PR TITLE
support end === -1 on re-encode

### PR DESCRIPTION
**Pull request by mafintosh**
this fixes an issue where the length would be set to an invalid number when re-encoding live streaming webm files.

### CODE REVIEW

**Comment by themasch** [comment]
Do you think there is a way to unit-test that? It looks good to me but I'd really like to see it checked by tests.

**Comment by mafintosh** [comment]
Yea np. Let me add a test.

**Comment by mafintosh** [comment]
@themasch added a test for it

**Comment by themasch** [comment]
I would release it as v2.2, alright?

**Comment by mafintosh** [comment]
Yea that sounds about right. Thanks a lot.

**Pull request merged**
