### PR TITLE
stream transform encoder and decoder

### PR DESCRIPTION
**Pull request by owcd**
We converted the decoder and encoder into transform streams. This allows us to use them as input / output of a pipeline. Within the pipeline it is much easier to deal with the parsed data to monitor or modify it.

### CODE REVIEW

**Comment by owcd** [comment]
Looks like this works only with nodejs 0.12 and above.

**Comment by themasch** [comment]
I'm not really sure but your changes look like you need to change the unit tests in order to pass them.
And could you add 0.12 and 4.0 to the travis.yml?

**Comment by owcd** [comment]
Sure, updated the test cases and added one for testing the decoder/encoder pipeline. Also changed travis.yml to build for 0.12 and 4.0.

**Comment by themasch** [comment]
okay since this PR changes the API and dependencies, it should get a new major version number. 2.0.0 should be fine. I'll merge it later today (hopefully).

**Comment by owcd** [comment]
Thanks. Yes, a new major version number is certainly required.

**Comment by themasch** [comment]
merged, version updated & published. please test. 
Thanks for the contribution!

**Comment by owcd** [comment]
Thanks, works perfect!

**Pull request merged**
